import "ItemsViewModel.idl";


namespace App1
{
    [default_interface]
    runtimeclass FinishPage : Microsoft.UI.Xaml.Controls.Page
    {
        FinishPage();

        ItemsViewModel ViewModel{ get; };
    }
}
