namespace App1
{
    [default_interface]
    runtimeclass Item
    {
        Item();
        String Name;
        String Asset;
    }
    
    [default_interface]
    runtimeclass ItemsViewModel
    {
        ItemsViewModel();

        Windows.Foundation.Collections.IObservableVector<Item> Items();
    }
}
